version: "3.2"

services:
  dev:
    container_name: subdex-node
    image: subdarkdex/subdex-chain:latest
    working_dir: /var/www/subdex-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/subdex-node/.cargo
    volumes:
      - .:/var/www/subdex-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/subdex-node --dev --ws-external"
